---

- name: Test if saved Oracle Docker image exists
  stat:
    path: "{{ docker_image_directory }}/oradb-12201-ee.tgz"
  register: docker_image_oracle

# Execute docker load command instead of docker_image due to bug with large files

- name: Get Oracle Docker image facts
  docker_image_facts:
    name: oracle/database:12.2.0.1-ee
  register: docker_oracle

- name: Load Oracle RDBMS Docker image
  command: docker load -i "{{ docker_image_directory }}/oradb-12201-ee.tgz"
  when: docker_image_oracle.stat.exists and docker_oracle.images | length == 0